In [11]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   黃淑芬  女  66  40  90  97  79
7   劉建宏  男  82  46  59  45  61
8   吳佳蓉  女  67  48  71  94  41
9   蔡宗翰  男  70  82  51  84  69
10  鄭宜君  女  69  78  73  61  98

In [16]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理  歷史
1   陳偉明  男  51  88  79  99  45
3   張家豪  男  52  68  68  45  44
11  周俊傑  男  40  73  92  62  97
12  許晴雅  女  41  62  70  81  84
14  楊雅筑  女  50  58  75  77  89
15  吳宗翰  男  55  43  95  96  88
18  何美好  女  54  41  73  51  64
21  謝承翰  男  48  86  80  85  53
27  江志偉  男  42  81  90  72  85
28  潘雨彤  女  42  80  59  53  61
29  盧俊宏  男  51  72  56  89  95
34  廖信傑  男  52  71  54  65  40
35  范揚名  男  55  44  48  84  82
36  郭雅萍  女  50  64  43  48  75
46  沈怡伶  女  50  81  58  62  49
50  韓雪梅  女  52  81  90  59  80

In [18]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
12  許晴雅  女  41  62  70  81  84
14  楊雅筑  女  50  58  75  77  89
18  何美好  女  54  41  73  51  64
28  潘雨彤  女  42  80  59  53  61
36  郭雅萍  女  50  64  43  48  75
46  沈怡伶  女  50  81  58  62  49
50  韓雪梅  女  52  81  90  59  80

In [19]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別  國文   英文  數學  地理  歷史   總分    平均    排名
43  傅子軒  男  94   76  89  76  85  420  84.0   1.0
16  徐曉萍  女  91   95  72  77  76  411  82.2   2.0
20  鄭雅琪  女  78   97  95  85  56  411  82.2   2.0
37  石智中  男  99  100  48  84  77  408  81.6   4.0
38  洪婉婷  女  98   78  58  94  77  405  81.0   5.0
23  簡宏達  男  83   73  72  83  91  402  80.4   6.0
26  曾怡慈  女  68   71  68  94  95  396  79.2   7.0
2   林雅婷  女  90   55  63  93  93  394  78.8   8.0
22  羅文婷  女  86   78  79  53  97  393  78.6   9.0
48  程文靜  女  79   86  78  65  81  389  77.8  10.0
47  莊承翰  男  78   53  90  74  91  386  77.2  11.0
39  翁英傑  男  69   57  96  66  94  382  76.4  12.0
10  鄭宜君  女  69   78  73  61  98  379  75.8  13.0
45  白明哲  男  67  100  93  75  44  379  75.8  13.0
15  吳宗翰  男  55   43  95  96  88  377  75.4  15.0
4   王美玲  女  76   58  55  99  85  373  74.6  16.0
6   黃淑芬  女  66   40  90  97  79  372  74.4  17.0
27  江志偉  男  42   81  90  72  85  370  74.0  18.0
41  鄧志誠  男  92   62  64  68  83  369  73.8  19.0
11  周俊傑  男  40   73  92  62  97  364  72.8  20.0
29  盧俊宏  男  51   72  56  89  95  363  72.6  21.0
1   陳偉明  男  51   88  79  99  45  362  72.4  22.0
50  韓雪梅  女  52   81  90  59  80  362  72.4  22.0
9   蔡宗翰  男  70   82  51  84  69  356  71.2  24.0
44  呂欣怡  女  95   59  51  77  73  355  71.0  25.0
49  蘇建宏  男  84   93  93  41  43  354  70.8  26.0
21  謝承翰  男  48   86  80  85  53  352  70.4  27.0
14  楊雅筑  女  50   58  75  77  89  349  69.8  28.0
5   李志偉  男  65   92  58  74  55  344  68.8  29.0
33  蔡宜珊  女  72   74  92  48  55  341  68.2  30.0
12  許晴雅  女  41   62  70  81  84  338  67.6  31.0
31  方信堯  男  60   63  88  70  53  334  66.8  32.0
19  胡育誠  男  88   90  41  49  64  332  66.4  33.0
24  詹宜臻  女  69   65  52  65  81  332  66.4  33.0
40  高于婷  女  60   61  53  76  76  326  65.2  35.0
42  溫佳蓉  女  81   64  44  90  46  325  65.0  36.0
32  鍾沛絜  女  67   62  73  73  48  323  64.6  37.0
8   吳佳蓉  女  67   48  71  94  41  321  64.2  38.0
30  葉庭妤  女  63   81  50  61  63  318  63.6  39.0
35  范揚名  男  55   44  48  84  82  313  62.6  40.0
13  賴威廷  男  64   44  47  88  69  312  62.4  41.0
25  邱顯杰  男  84   58  52  51  55  300  60.0  42.0
17  朱志豪  男  84   64  51  45  56  300  60.0  42.0
46  沈怡伶  女  50   81  58  62  49  300  60.0  42.0
28  潘雨彤  女  42   80  59  53  61  295  59.0  45.0
7   劉建宏  男  82   46  59  45  61  293  58.6  46.0
18  何美好  女  54   41  73  51  64  283  56.6  47.0
34  廖信傑  男  52   71  54  65  40  282  56.4  48.0
36  郭雅萍  女  50   64  43  48  75  280  56.0  49.0
3   張家豪  男  52   68  68  45  44  277  55.4  50.0

In [31]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['不及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

     姓名 性別  國文   英文  數學  地理  歷史   總分    平均    排名  及格的科目數  不及格的科目數
1   陳偉明  男  51   88  79  99  45  362  72.4  22.0       2        2
2   林雅婷  女  90   55  63  93  93  394  78.8   8.0       1        1
3   張家豪  男  52   68  68  45  44  277  55.4  50.0       3        3
4   王美玲  女  76   58  55  99  85  373  74.6  16.0       2        2
5   李志偉  男  65   92  58  74  55  344  68.8  29.0       2        2
6   黃淑芬  女  66   40  90  97  79  372  74.4  17.0       1        1
7   劉建宏  男  82   46  59  45  61  293  58.6  46.0       3        3
8   吳佳蓉  女  67   48  71  94  41  321  64.2  38.0       2        2
9   蔡宗翰  男  70   82  51  84  69  356  71.2  24.0       1        1
10  鄭宜君  女  69   78  73  61  98  379  75.8  13.0       0        0
11  周俊傑  男  40   73  92  62  97  364  72.8  20.0       1        1
12  許晴雅  女  41   62  70  81  84  338  67.6  31.0       1        1
13  賴威廷  男  64   44  47  88  69  312  62.4  41.0       2        2
14  楊雅筑  女  50   58  75  77  89  349  69.8  28.0       2        2
15  吳宗翰  男  55   43  95  96  88  377  75.4  15.0       2        2
16  徐曉萍  女  91   95  72  77  76  411  82.2   2.0       0        0
17  朱志豪  男  84   64  51  45  56  300  60.0  42.0       3        3
18  何美好  女  54   41  73  51  64  283  56.6  47.0       3        3
19  胡育誠  男  88   90  41  49  64  332  66.4  33.0       2        2
20  鄭雅琪  女  78   97  95  85  56  411  82.2   2.0       1        1
21  謝承翰  男  48   86  80  85  53  352  70.4  27.0       2        2
22  羅文婷  女  86   78  79  53  97  393  78.6   9.0       1        1
23  簡宏達  男  83   73  72  83  91  402  80.4   6.0       0        0
24  詹宜臻  女  69   65  52  65  81  332  66.4  33.0       1        1
25  邱顯杰  男  84   58  52  51  55  300  60.0  42.0       4        4
26  曾怡慈  女  68   71  68  94  95  396  79.2   7.0       0        0
27  江志偉  男  42   81  90  72  85  370  74.0  18.0       1        1
28  潘雨彤  女  42   80  59  53  61  295  59.0  45.0       3        3
29  盧俊宏  男  51   72  56  89  95  363  72.6  21.0       2        2
30  葉庭妤  女  63   81  50  61  63  318  63.6  39.0       1        1
31  方信堯  男  60   63  88  70  53  334  66.8  32.0       1        1
32  鍾沛絜  女  67   62  73  73  48  323  64.6  37.0       1        1
33  蔡宜珊  女  72   74  92  48  55  341  68.2  30.0       2        2
34  廖信傑  男  52   71  54  65  40  282  56.4  48.0       3        3
35  范揚名  男  55   44  48  84  82  313  62.6  40.0       3        3
36  郭雅萍  女  50   64  43  48  75  280  56.0  49.0       3        3
37  石智中  男  99  100  48  84  77  408  81.6   4.0       1        1
38  洪婉婷  女  98   78  58  94  77  405  81.0   5.0       1        1
39  翁英傑  男  69   57  96  66  94  382  76.4  12.0       1        1
40  高于婷  女  60   61  53  76  76  326  65.2  35.0       1        1
41  鄧志誠  男  92   62  64  68  83  369  73.8  19.0       0        0
42  溫佳蓉  女  81   64  44  90  46  325  65.0  36.0       2        2
43  傅子軒  男  94   76  89  76  85  420  84.0   1.0       0        0
44  呂欣怡  女  95   59  51  77  73  355  71.0  25.0       2        2
45  白明哲  男  67  100  93  75  44  379  75.8  13.0       1        1
46  沈怡伶  女  50   81  58  62  49  300  60.0  42.0       3        3
47  莊承翰  男  78   53  90  74  91  386  77.2  11.0       1        1
48  程文靜  女  79   86  78  65  81  389  77.8  10.0       0        0
49  蘇建宏  男  84   93  93  41  43  354  70.8  26.0       2        2
50  韓雪梅  女  52   81  90  59  80  362  72.4  22.0       2        2

In [32]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別  國文   英文  數學  地理  歷史   總分    平均    排名  及格的科目數  不及格的科目數     不及格的科目名稱
1   陳偉明  男  51   88  79  99  45  362  72.4  22.0       2        2        國文,歷史
2   林雅婷  女  90   55  63  93  93  394  78.8   8.0       1        1           英文
3   張家豪  男  52   68  68  45  44  277  55.4  50.0       3        3     國文,地理,歷史
4   王美玲  女  76   58  55  99  85  373  74.6  16.0       2        2        英文,數學
5   李志偉  男  65   92  58  74  55  344  68.8  29.0       2        2        數學,歷史
6   黃淑芬  女  66   40  90  97  79  372  74.4  17.0       1        1           英文
7   劉建宏  男  82   46  59  45  61  293  58.6  46.0       3        3     英文,數學,地理
8   吳佳蓉  女  67   48  71  94  41  321  64.2  38.0       2        2        英文,歷史
9   蔡宗翰  男  70   82  51  84  69  356  71.2  24.0       1        1           數學
10  鄭宜君  女  69   78  73  61  98  379  75.8  13.0       0        0            無
11  周俊傑  男  40   73  92  62  97  364  72.8  20.0       1        1           國文
12  許晴雅  女  41   62  70  81  84  338  67.6  31.0       1        1           國文
13  賴威廷  男  64   44  47  88  69  312  62.4  41.0       2        2        英文,數學
14  楊雅筑  女  50   58  75  77  89  349  69.8  28.0       2        2        國文,英文
15  吳宗翰  男  55   43  95  96  88  377  75.4  15.0       2        2        國文,英文
16  徐曉萍  女  91   95  72  77  76  411  82.2   2.0       0        0            無
17  朱志豪  男  84   64  51  45  56  300  60.0  42.0       3        3     數學,地理,歷史
18  何美好  女  54   41  73  51  64  283  56.6  47.0       3        3     國文,英文,地理
19  胡育誠  男  88   90  41  49  64  332  66.4  33.0       2        2        數學,地理
20  鄭雅琪  女  78   97  95  85  56  411  82.2   2.0       1        1           歷史
21  謝承翰  男  48   86  80  85  53  352  70.4  27.0       2        2        國文,歷史
22  羅文婷  女  86   78  79  53  97  393  78.6   9.0       1        1           地理
23  簡宏達  男  83   73  72  83  91  402  80.4   6.0       0        0            無
24  詹宜臻  女  69   65  52  65  81  332  66.4  33.0       1        1           數學
25  邱顯杰  男  84   58  52  51  55  300  60.0  42.0       4        4  英文,數學,地理,歷史
26  曾怡慈  女  68   71  68  94  95  396  79.2   7.0       0        0            無
27  江志偉  男  42   81  90  72  85  370  74.0  18.0       1        1           國文
28  潘雨彤  女  42   80  59  53  61  295  59.0  45.0       3        3     國文,數學,地理
29  盧俊宏  男  51   72  56  89  95  363  72.6  21.0       2        2        國文,數學
30  葉庭妤  女  63   81  50  61  63  318  63.6  39.0       1        1           數學
31  方信堯  男  60   63  88  70  53  334  66.8  32.0       1        1           歷史
32  鍾沛絜  女  67   62  73  73  48  323  64.6  37.0       1        1           歷史
33  蔡宜珊  女  72   74  92  48  55  341  68.2  30.0       2        2        地理,歷史
34  廖信傑  男  52   71  54  65  40  282  56.4  48.0       3        3     國文,數學,歷史
35  范揚名  男  55   44  48  84  82  313  62.6  40.0       3        3     國文,英文,數學
36  郭雅萍  女  50   64  43  48  75  280  56.0  49.0       3        3     國文,數學,地理
37  石智中  男  99  100  48  84  77  408  81.6   4.0       1        1           數學
38  洪婉婷  女  98   78  58  94  77  405  81.0   5.0       1        1           數學
39  翁英傑  男  69   57  96  66  94  382  76.4  12.0       1        1           英文
40  高于婷  女  60   61  53  76  76  326  65.2  35.0       1        1           數學
41  鄧志誠  男  92   62  64  68  83  369  73.8  19.0       0        0            無
42  溫佳蓉  女  81   64  44  90  46  325  65.0  36.0       2        2        數學,歷史
43  傅子軒  男  94   76  89  76  85  420  84.0   1.0       0        0            無
44  呂欣怡  女  95   59  51  77  73  355  71.0  25.0       2        2        英文,數學
45  白明哲  男  67  100  93  75  44  379  75.8  13.0       1        1           歷史
46  沈怡伶  女  50   81  58  62  49  300  60.0  42.0       3        3     國文,數學,歷史
47  莊承翰  男  78   53  90  74  91  386  77.2  11.0       1        1           英文
48  程文靜  女  79   86  78  65  81  389  77.8  10.0       0        0            無
49  蘇建宏  男  84   93  93  41  43  354  70.8  26.0       2        2        地理,歷史
50  韓雪梅  女  52   81  90  59  80  362  72.4  22.0       2        2        國文,地理