In [11]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   黃淑芬  女  66  40  90  97  79
7   劉建宏  男  82  46  59  45  61
8   吳佳蓉  女  67  48  71  94  41
9   蔡宗翰  男  70  82  51  84  69
10  鄭宜君  女  69  78  73  61  98

In [16]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理  歷史
1   陳偉明  男  51  88  79  99  45
3   張家豪  男  52  68  68  45  44
11  周俊傑  男  40  73  92  62  97
12  許晴雅  女  41  62  70  81  84
14  楊雅筑  女  50  58  75  77  89
15  吳宗翰  男  55  43  95  96  88
18  何美好  女  54  41  73  51  64
21  謝承翰  男  48  86  80  85  53
27  江志偉  男  42  81  90  72  85
28  潘雨彤  女  42  80  59  53  61
29  盧俊宏  男  51  72  56  89  95
34  廖信傑  男  52  71  54  65  40
35  范揚名  男  55  44  48  84  82
36  郭雅萍  女  50  64  43  48  75
46  沈怡伶  女  50  81  58  62  49
50  韓雪梅  女  52  81  90  59  80

In [18]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
12  許晴雅  女  41  62  70  81  84
14  楊雅筑  女  50  58  75  77  89
18  何美好  女  54  41  73  51  64
28  潘雨彤  女  42  80  59  53  61
36  郭雅萍  女  50  64  43  48  75
46  沈怡伶  女  50  81  58  62  49
50  韓雪梅  女  52  81  90  59  80