In [1]:
import pandas as pd

df = pd.DataFrame({
    "學生姓名": ["王小明", "趙冠宇", "李小華", "趙冠宇"],
    "分數": [80, 95, 72, 88]
})

df[df["學生姓名"] == "趙冠宇"]

  學生姓名  分數
1  趙冠宇  95
3  趙冠宇  88

In [2]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
df[df["學生姓名"] == "趙冠宇"]
#print(zhao)

   學生姓名  語文  數學  英語  物理  化學
10  趙冠宇  85  82  88  84  86

In [3]:
import pandas as pd

df = pd.read_csv("考試分數_3年6班.csv")
df[df["學生姓名"] == "洪婉婷"]

   學生姓名  語文  數學  英語  物理  化學
14  洪婉婷  88  86  90  88  86